// Code generated by entc, DO NOT EDIT.

package pet

const (
	Label = "pet"
	FieldID = "id"
	FieldName = "name"
	FieldAge = "age"
	EdgeOwner = "owner"
	Table = "pets"
	OwnerTable = "pets"
	OwnerInverseTable = "users"
	OwnerColumn = "user_pets"
)

var Columns = []string{
	FieldID,
	FieldName,
	//FieldAge,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_pets",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
)
