// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateTodoRes interface {
	createTodoRes()
}

type CreateUsersRes interface {
	createUsersRes()
}

type DeleteTodoRes interface {
	deleteTodoRes()
}

type DeleteUsersRes interface {
	deleteUsersRes()
}

type ListTodoRes interface {
	listTodoRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type ReadTodoRes interface {
	readTodoRes()
}

type ReadUsersRes interface {
	readUsersRes()
}

type UpdateTodoRes interface {
	updateTodoRes()
}

type UpdateUsersRes interface {
	updateUsersRes()
}
