// Code generated by entc, DO NOT EDIT.

package users

import (
	"time"
)

const (
	// Label holds the string label denoting the users type in the database.
	Label = "users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldFirst holds the string denoting the first field in the database.
	FieldFirst = "first"
	// FieldStart holds the string denoting the start field in the database.
	FieldStart = "start"
	// FieldDraw holds the string denoting the draw field in the database.
	FieldDraw = "draw"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the users in the database.
	Table = "users"
)

// Columns holds all SQL columns for users fields.
var Columns = []string{
	FieldID,
	FieldUser,
	FieldFirst,
	FieldStart,
	FieldDraw,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserValidator is a validator for the "user" field. It is called by the builders before save.
	UserValidator func(string) error
	// DefaultFirst holds the default value on creation for the "first" field.
	DefaultFirst int
	// DefaultStart holds the default value on creation for the "start" field.
	DefaultStart bool
	// DefaultDraw holds the default value on creation for the "draw" field.
	DefaultDraw int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
