// Code generated by entc, DO NOT EDIT.

package user

const (
	Label = "user"
	FieldID = "id"
	FieldName = "name"
	FieldAge = "age"
	FieldCard = "card"
	FieldUpdatedAt = "updated_at"
	FieldCreatedAt = "created_at"
	EdgePets = "pets"
	Table = "users"
	PetsTable = "pets"
	PetsInverseTable = "pets"
	PetsColumn = "user_pets"
)

var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
