// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
